# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_data.proto\"\x85\x02\n\nSensorData\x12\x10\n\x08sequence\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x1c\n\x03imu\x18\x03 \x01(\x0b\x32\x0f.SensorData.IMU\x12\x1c\n\x03gps\x18\x04 \x01(\x0b\x32\x0f.SensorData.GPS\x1ah\n\x03IMU\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x01 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x02 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x03 \x01(\x02\x12\x0e\n\x06gyro_x\x18\x04 \x01(\x02\x12\x0e\n\x06gyro_y\x18\x05 \x01(\x02\x12\x0e\n\x06gyro_z\x18\x06 \x01(\x02\x1a,\n\x03GPS\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\x0b\n\x03\x61lt\x18\x03 \x01(\x02\"K\n\x07\x43ommand\x12\x10\n\x08sequence\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORDATA._serialized_start=22
  _SENSORDATA._serialized_end=283
  _SENSORDATA_IMU._serialized_start=133
  _SENSORDATA_IMU._serialized_end=237
  _SENSORDATA_GPS._serialized_start=239
  _SENSORDATA_GPS._serialized_end=283
  _COMMAND._serialized_start=285
  _COMMAND._serialized_end=360
# @@protoc_insertion_point(module_scope)
