/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "robot_messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SensorData, SensorData, AUTO)


PB_BIND(SensorData_IMU, SensorData_IMU, AUTO)


PB_BIND(SensorData_GPS, SensorData_GPS, AUTO)


PB_BIND(RobotStatus, RobotStatus, AUTO)


PB_BIND(Command, Command, AUTO)



