/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SENSOR_DATA_PB_H_INCLUDED
#define PB_SENSOR_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorData_IMU {
    float accel_x;
    float accel_y;
    float accel_z;
    float gyro_x;
    float gyro_y;
    float gyro_z;
} SensorData_IMU;

typedef struct _SensorData_GPS {
    float lat;
    float lon;
    float alt;
} SensorData_GPS;

typedef struct _SensorData {
    uint32_t sequence;
    float timestamp;
    bool has_imu;
    SensorData_IMU imu;
    bool has_gps;
    SensorData_GPS gps;
} SensorData;

typedef struct _Command {
    uint32_t sequence;
    float timestamp;
    pb_callback_t type;
    float value;
} Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorData_init_default                  {0, 0, false, SensorData_IMU_init_default, false, SensorData_GPS_init_default}
#define SensorData_IMU_init_default              {0, 0, 0, 0, 0, 0}
#define SensorData_GPS_init_default              {0, 0, 0}
#define Command_init_default                     {0, 0, {{NULL}, NULL}, 0}
#define SensorData_init_zero                     {0, 0, false, SensorData_IMU_init_zero, false, SensorData_GPS_init_zero}
#define SensorData_IMU_init_zero                 {0, 0, 0, 0, 0, 0}
#define SensorData_GPS_init_zero                 {0, 0, 0}
#define Command_init_zero                        {0, 0, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorData_IMU_accel_x_tag               1
#define SensorData_IMU_accel_y_tag               2
#define SensorData_IMU_accel_z_tag               3
#define SensorData_IMU_gyro_x_tag                4
#define SensorData_IMU_gyro_y_tag                5
#define SensorData_IMU_gyro_z_tag                6
#define SensorData_GPS_lat_tag                   1
#define SensorData_GPS_lon_tag                   2
#define SensorData_GPS_alt_tag                   3
#define SensorData_sequence_tag                  1
#define SensorData_timestamp_tag                 2
#define SensorData_imu_tag                       3
#define SensorData_gps_tag                       4
#define Command_sequence_tag                     1
#define Command_timestamp_tag                    2
#define Command_type_tag                         3
#define Command_value_tag                        4

/* Struct field encoding specification for nanopb */
#define SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    timestamp,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  imu,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps,               4)
#define SensorData_CALLBACK NULL
#define SensorData_DEFAULT NULL
#define SensorData_imu_MSGTYPE SensorData_IMU
#define SensorData_gps_MSGTYPE SensorData_GPS

#define SensorData_IMU_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_x,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_y,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_z,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_x,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_y,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_z,            6)
#define SensorData_IMU_CALLBACK NULL
#define SensorData_IMU_DEFAULT NULL

#define SensorData_GPS_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    lat,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    lon,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    alt,               3)
#define SensorData_GPS_CALLBACK NULL
#define SensorData_GPS_DEFAULT NULL

#define Command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    timestamp,         2) \
X(a, CALLBACK, SINGULAR, STRING,   type,              3) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             4)
#define Command_CALLBACK pb_default_field_callback
#define Command_DEFAULT NULL

extern const pb_msgdesc_t SensorData_msg;
extern const pb_msgdesc_t SensorData_IMU_msg;
extern const pb_msgdesc_t SensorData_GPS_msg;
extern const pb_msgdesc_t Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorData_fields &SensorData_msg
#define SensorData_IMU_fields &SensorData_IMU_msg
#define SensorData_GPS_fields &SensorData_GPS_msg
#define Command_fields &Command_msg

/* Maximum encoded size of messages (where known) */
/* Command_size depends on runtime parameters */
#define SENSOR_DATA_PB_H_MAX_SIZE                SensorData_size
#define SensorData_GPS_size                      15
#define SensorData_IMU_size                      30
#define SensorData_size                          60

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
